version: 'version 3'
services:
  flask:
    build: ./flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
  node:
    build: ./node
    ports:
      - "8080:8080"
    depends_on:
      - flask
    links:
      - flask